spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/safeat
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  config:
    activate:
      on-profile: local
oauth:
  google:
    client-id: "local"
    redirect-uri: "local"
    client-secret: "client-secret"
jwt:
  secret: "ToiguaOaVf3o3wD8XSnJV10MlWo0exackfAofpscMqs="

---

spring:
  config:
    import: classpath:secret/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:secret/application-prod.yml
    activate:
      on-profile: prod
