spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
google:
  credentialPath: "local"
  ocr:
    projectId: "local"
    location: "local"
    processorId: "local"
  oauth:
    client-id: "local"
    redirect-uri: "local"
    client-secret: "client-secret"

jwt:
  secret: "ToiguaOaVf3o3wD8XSnJV10MlWo0exackfAofpscMqs="

---

spring:
  config:
    import: classpath:secret/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:secret/application-prod.yml
    activate:
      on-profile: prod
