name: Safeat Backend Prod Server CD

on:
  workflow_dispatch:

jobs:
  build:
    name: 빌드
    runs-on: ubuntu-22.04
    steps:
      - name: workflow_dispatch에서 지정한 branch로 checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: JDK 17로 설정
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Gradle에 실행 권한 부여
        run: chmod +x gradlew

      - name: jar artifact에 업로드
        uses: actions/upload-artifact@v3
        with:
          name: BackendApplicationJar
          path: build/libs/safeat-0.0.1-SNAPSHOT.jar

  deploy:
    runs-on: self-hosted
    needs: build-and-upload
    steps:
      - name: 구버전 jar 삭제
        run: rm -rf /home/hong/build/safeat-0.0.1-SNAPSHOT.jar
      - name: artifact에서 jar파일 다운 받기
        uses: actions/download-artifact@v3
        with:
          name: BackendApplicationJar
          path: /home/hong/build/
      - name: 배포하기
        run: /home/hong/build/deploy.sh
