name: Safeat Backend Prod Server CD

on:
  workflow_dispatch:

jobs:
  build:
    name: 빌드
    runs-on: ubuntu-22.04
    outputs:
      current_timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: workflow_dispatch에서 지정한 branch로 checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: JDK 17로 설정
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      - name: unix 타임스탬프 얻기
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +%s)"

      - name: unix 타임스탬프 확인하기
        run: echo ${{ steps.timestamp.outputs.timestamp }}

      - name: Gradle에 실행 권한 부여
        run: chmod +x gradlew

      - name: Update submodule
        run: |
          git submodule update --remote --recursive
        env:
          TOKEN: ${{ secrets.SUBMODULE_TOKEN }}

      - name: 도커 빌더 생성 및 부팅
        uses: docker/setup-buildx-action@v2

      - name: 도커 허브에 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 도커 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-prod
          platforms: linux/64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/safeat:${{ steps.timestamp.outputs.timestamp }}

  deploy:
    needs: build
    name: 배포
    runs-on: self-hosted
    steps:
      - name: 도커 실행
        run:
          sudo /home/ubuntu/deploy.sh ${{ secrets.DOCKERHUB_USERNAME }} ${{ needs.build.outputs.current_timestamp }}